steps:
  - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@2
    displayName: Install signing plugin
    inputs:
      signType: $(SignType)

  - task: DownloadPipelineArtifact@2
    displayName: Download unsigned installer
    inputs:
      artifact: _osx_installer_unsigned
      path: $(Build.StagingDirectory)\package

  # Must use the NuGet & MSBuild toolchain here rather than `dotnet`
  # because the signing tasks target the netfx MSBuild runtime only.
  - task: NuGetCommand@2
    displayName: Restore MicroBuild packages
    inputs:
      command: restore
      restoreSolution: 'Scalar.Signing\Scalar.SignPackage.Mac.csproj'

  - task: MSBuild@1
    displayName: Sign installer package
    inputs:
      solution: 'Scalar.Signing\Scalar.SignPackage.Mac.csproj'
      msbuildArguments: '/p:RootDir="$(Build.ArtifactStagingDirectory)\package"'

  - task: PublishPipelineArtifact@1
    displayName: Publish signed installer
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)\package
      artifactName: _osx_installer_signed
