steps:
  - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@2
    displayName: Install signing plugin
    inputs:
      signType: $(SignType)
    condition: and(succeeded(), ne(variables['SignType'], ''))

  - task: UseDotNet@2
    displayName: Use .NET Core SDK 3.1.101
    inputs:
      packageType: sdk
      version: 3.1.101

  - script: $(Build.Repository.LocalPath)\\Scripts\\NukeBuildOutputs.bat
    displayName: Delete previous build outputs
    continueOnError: true

  - script: $(Build.Repository.LocalPath)\.azure-pipelines\templates\win\install-git-package.bat
    displayName: Setup Git installer

  - script: $(Build.Repository.LocalPath)\Scripts\BuildScalarForWindows.bat $(configuration) $(majorAndMinorVersion).$(revision)
    displayName: Build Scalar ($(configuration))

  - task: PublishTestResults@2
    displayName: Publish unit test results
    inputs:
      testRunner: VSTest
      testResultsFiles: "**\\*.trx"
      searchFolder: $(Common.TestResultsDirectory)
      testRunTitle: Windows $(configuration) Unit Tests
      publishRunAttachments: true
    condition: succeededOrFailed()
