steps:
  - task: UseDotNet@2
    displayName: Use .NET Core SDK 3.1.101
    inputs:
      packageType: sdk
      version: 3.1.101

  - script: $(Build.Repository.LocalPath)/Scripts/Mac/NukeBuildOutputs.sh
    displayName: Delete previous build outputs
    continueOnError: true

  - script: |
      GIT_VERSION=$(grep '<GitPackageVersion>' Directory.Build.props | grep -Eo '[0-9.]+(-\w+)*')
      mkdir ../out
      cd ../out
      dotnet new classlib -n Scalar.GitInstaller
      cd Scalar.GitInstaller
      dotnet add Scalar.GitInstaller.csproj package "GitForMac.GVFS.Installer" --package-directory . --version "$GIT_VERSION" --source "https://pkgs.dev.azure.com/gvfs/ci/_packaging/Dependencies/nuget/v3/index.json"
    displayName: Setup Git installer

  - script: Scripts/Mac/BuildScalarForMac.sh $(configuration) $(majorAndMinorVersion).$(revision)
    displayName: Build Scalar ($(configuration))

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      searchFolder: $(Common.TestResultsDirectory)
      testRunTitle: Mac $(configuration) Unit Tests
      publishRunAttachments: true
    condition: succeededOrFailed()
